name: example workflow

on: 
  create:
    branches:
      - release/**

jobs:
  first-example:
      env:
        GH_TOKEN: ${{ github.token }}
      runs-on: ubuntu-latest    
      steps:
        - name: Checkout branch
          uses: actions/checkout@v3
        - name: Create version-bump-branch
          run: |
            git checkout -b version-bump
        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: "16"
            cache: "npm"
        - name: npm install
          run: npm ci
        - name: Create changelog  
          run: | 
            git config user.name github-actions
            git config user.email github-actions@github.com
            npm run version
            git add .
            git commit -m "chore(package.json): changelog & version bump"
        - name: Push changes to version-bump branch
          run: |
            git push --set-upstream origin version-bump
            gh pr create --draft --title "New version bump available" --body "Sample Text"  --base main --head version-bump