name: version-bump

on: 
  create:
    branches:
      - release/**

jobs:
  first-example:
      env:
        GH_TOKEN: ${{ github.token }}
      runs-on: ubuntu-latest    
      steps:
        - name: Checkout branch
          uses: actions/checkout@v3
        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: "16"
            cache: "npm"
        - name: Run npm install
          run: npm install
        - name: Create changelog  
          run: | 
            npm run version
        - name: Create and switch to version-bump-branch
          run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git checkout -b version-bump
            git add .
            git commit -m "chore(package.json): changelog & version bump"
        - name: Detect PR
          id: detect-pr
          run: echo "action_state= git ls-remote --heads git@github.com:user/repo.git branch-name | wc -l"
        - name: Push changes to version-bump branch 
          if: ${{ env.action_state == 0 }}
          run: |
              git push --set-upstream origin version-bump
              gh pr create --draft --title "New version bump available" --body "Update package.json version and check CHANGELOG.md before merging"  --base main --head version-bump
        - name: Skip version-bump branch
          if: ${{ env.action_state == 1 }}
          run:  echo "branch already exist"