name: example workflow

on: 
  push:
    branches:
      - main

jobs:
  first-example:
      runs-on: ubuntu-latest    
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Create version-bump-branch
          run: |
            git branch version-bump
            git push --set-upstream origin version-bump
            gh pr create --draft --title "New version bump available"  --base main --head version-bump
          with:
            GH_TOKEN: ${{ github.token }}





