name: pre-changelog

on: 
  push:
    branches:
      - release/**

jobs:
  pre-changelog:
      env:
        GH_TOKEN: ${{ github.token }}
        RELEASE_NAME: ${{  github.ref_name  }}
      runs-on: ubuntu-latest    
      steps:
        - name: Checkout branch
          uses: actions/checkout@v3
        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: "16"
            cache: "npm"
        - name: Run npm install
          run: npm ci
        - name: Configure actions user
          run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
        - name: Check remote for pre-changelog branch
          run: |
            echo "branchCheck=$( git ls-remote origin ${{ env.RELEASE_NAME }}__pre-changelog | wc -l )" >> $GITHUB_ENV
        - name: Create pre-changelog
          if: env.branchCheck == 0
          run: |
              git checkout -b ${{ env.RELEASE_NAME }}__pre-changelog
              npm run version
              git add .
              git commit -m "chore(CHANGELOG.md): new changelog"
              git push --set-upstream origin ${{ env.RELEASE_NAME }}__pre-changelog
              gh pr create --draft --title "New changelog available" --body "Check CHANGELOG.md before merging"  --base main --head ${{ env.RELEASE_NAME }}__pre-changelog
        - name: Update pre-changelog
          if: env.branchCheck == 1
          run: |
              git fetch --all
              git checkout ${{ env.RELEASE_NAME }}__pre-changelog
              npm run version
              git add .
              git commit -m "chore(CHANGELOG.md): new changelog"
              git push 