name: pre-bump

on: 
  push:
    branches:
      - release/**

jobs:
  pre-bump:
      env:
        GH_TOKEN: ${{ github.token }}
        RELEASE_BRANCH_NAME: ${{ github.ref_name }}
      runs-on: ubuntu-latest    
      steps:
        - name: view
          run: echo ${{ env.RELEASE_BRANCH_NAME }}
        - name: Checkout branch
          uses: actions/checkout@v3
        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: "16"
            cache: "npm"
        - name: Run npm install
          run: npm ci
        - name: Configure actions user
          run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
        - name: Check remote for pre-bump branch
          run: |
            echo "branchCheck=$( git ls-remote origin pre-bump | wc -l )" >> $GITHUB_ENV
        - name: Create pre-bump
          if: env.branchCheck == 0
          run: |
              git checkout -b pre-bump
              npm run version
              git add .
              git commit -m "chore(package.json): changelog & version bump"
              git push --set-upstream origin pre-bump
              gh pr create --draft --title "New version bump available" --body "Update package.json version and check CHANGELOG.md before merging"  --base main --head pre-bump
        - name: Update pre-bump
          if: env.branchCheck == 1
          run: |
              git fetch --all
              git checkout pre-bump
              npm run version
              git add .
              git commit -m "chore(package.json): changelog & version bump update"
              git push 