name: version-bump

on: 
  push:
    branches:
      - release/**

jobs:
  version-bump:
      env:
        GH_TOKEN: ${{ github.token }}
      runs-on: ubuntu-latest    
      steps:
        - name: Checkout branch
          uses: actions/checkout@v3
        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: "16"
            cache: "npm"
        - name: Run npm install
          run: npm install
        - name: Configure actions user
          run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
        - name: Create changelog
          run: | 
            npm run version
        - name: Check for remotebranch
          run: echo "BRANCH_EXISTS = git ls-remote --heads git@github.com:JsantanaRoman/actions-test.git version-bump | wc -l" >> $GITHUB_ENV
        - name: View result
          if: ${{ !env.BRANCH_EXISTS }}
          run: echo "$env.BRANCH_EXISTS"
        - name: Create and switch to version-bump-branch
          run: |
            git checkout -b version-bump
            git add .
            git commit -m "chore(package.json): changelog & version bump"
        - name: Configure PR
          run: |
              git push --set-upstream origin version-bump
              gh pr create --draft --title "New version bump available" --body "Update package.json version and check CHANGELOG.md before merging"  --base main --head version-bump